title: My GitHub Page
description: "This is my awesome GitHub Pages site."
theme: minima
url: "https://your-github-username.github.io"
baseurl: "" # Nếu bạn sử dụng user/repo thì không cần baseurl
markdown: kramdown
plugins:
  - jekyll-seo-tag
title: My Awesome Site
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  SEO purposes) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yourusername.github.io" # the base hostname & protocol for your site
twitter_username: your-twitter-handle
github_username:  your-github-username

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
